core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('accounts/', include('usuarios.urls')),
    path('articles/', include('articulo.urls')),
    path('comentarios/', include('comentarios.urls')),
    path('', include('acercaDe.urls')),
    path('', include('contacto.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handling404 = 'views.handling_404'

usuarios/urls.py
from django.urls import path
from .views import *
from . import views

app_name="usuarios"

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login_user'), 
    path('signup/', CustomRegisterUserView.as_view(), {'next_page': None}, name='signup_user'),  
    path('logout/', CustomLogoutView.as_view(), name='logout_user'),  
    path('confirm_logout/', CustomConfirmLogoutView.as_view(), {'next_page': None}, name='confirm_logout_user'),

    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),

    path('update/', CustomUpdateUserView.as_view(), name='update_user'),
    path('change_password/', CustomPasswordChangeView.as_view(), name='change_password'),

    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

templates/data/myProfile/change_password.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<main class="container">
  <h1 class=" mb-4 text-center fs-6 text-decoration-underline">Cambia tu contraseña</h1>
    <div class="row justify-content-center">
      <div class="col-md-6">
        <form method="post">
          {% csrf_token %}
          {{form|crispy}}
          <div class="d-grid mt-4">
            <button class="btn btn-primary" type="submit">Guardar cambios</button>
          </div>
          <div class="d-grid mt-4">
            <a href="{% url 'usuarios:update_user' %}" class="btn btn-outline-secondary"> <b> Volver a mis Datos </b> </a> 
        </div>
        </form>
      </div>
    </div>
  </main>
{% endblock %}

templates/data/myProfile/update_user.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<main class="container">
  <h1  class=" mb-4 text-center fs-6 text-decoration-underline">Actualiza tus datos</h1>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <div class="d-grid mt-4">
          <button class="btn btn-primary" type="submit">Guardar cambios</button>
        </div>
        <div class="d-grid mt-4">
            <a href="{% url 'usuarios:change_password'%}"  class="btn btn-outline-secondary"> <b> Cambiar contraseña </b> </a> 
        </div>
      </form>
    </div>
  </div>
</main>
{% endblock %}