acercaDe/urls.py
from django.urls import path
from .views import *


app_name="About"

urlpatterns = [
    path('about/', AllAboutView.as_view(), name="about"),
]

articulo/urls.py
from django.urls import path
from .views import *


app_name="articulos"

urlpatterns = [

    path('create/', ArtCreateView.as_view(), name="article_create"),

    path('all-articles/', AllArticlesView.as_view(), name="all_articles"),

    path('all-category/', AllCategoriaView.as_view(), name="all_category"),

    path('category/<int:category_id>/', AllCategoriaArticlesView.as_view(), name='all_category_articles'),

    path('create-category/', CategoryCreateView.as_view(), name="create_category"),

    path('<int:pk>/delete-category/', CategoryDeleteView.as_view(), name="delete_category"),

    path('Article/<int:post_id>/', ArtDetailView.as_view(), name="detail_article"),

    path('<int:pk>/update/', ArtUpdateView.as_view(), name="update_article"),

    path('<int:pk>/delete-article/', ArtDeleteView.as_view(), name="delete_article"),

    path('like/<int:post_id>/', LikeHandler.as_view(), name="like"),
    
    path('dislike/<int:post_id>/', DislikeHandler.as_view(), name="dislike"),
]

contacto/urls.py
from django.urls import path
from .views import *

app_name = 'contacts'

urlpatterns = [
    path('Contact/', ContactView.as_view(), name = 'contact'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('accounts/', include('usuarios.urls')),
    path('articles/', include('articulo.urls')),
    path('comentarios/', include('comentarios.urls')),
    path('', include('acercaDe.urls')),
    path('', include('contacto.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handling404 = 'views.handling_404'

usuarios/urls.py
from django.urls import path
from .views import *
from . import views

app_name="usuarios"

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login_user'), 
    path('signup/', CustomRegisterUserView.as_view(), {'next_page': None}, name='signup_user'),  
    path('logout/', CustomLogoutView.as_view(), name='logout_user'),  
    path('confirm_logout/', CustomConfirmLogoutView.as_view(), {'next_page': None}, name='confirm_logout_user'),

    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),

    path('update/', CustomUpdateUserView.as_view(), name='update_user'),
    path('change_password/', CustomPasswordChangeView.as_view(), name='change_password'),

    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

templates/partials/footer.html
<footer class=" bg-dark text-center text-white">
  <!-- Contenedor -->
  <div class="container p-4 pb-0">
    <!-- Sección: Redes Sociales -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/REDSALUDCHACO" target="_blank" role="button"
        ><i class="bi bi-facebook"></i
      ></a>
      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/reddesaludchaco" target="_blank" role="button"
        ><i class="bi bi-instagram"></i
      ></a>
      <!-- Whatsapp -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://wa.me/543624664745" target="_blank" role="button"
        ><i class="bi bi-whatsapp"></i
      ></a>
      <!-- Mail -->
      <a class="btn btn-outline-light btn-floating m-1" href="mailto: reddesaludchaco@yahoo.com.ar" target="_blank" role="button"
        ><i class="bi bi-envelope"></i
      ></a>
    </section>
  </div>    
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright: GRUPO N° 25 (COMISIÓN 2 - CURSO "DESARROLLO WEB")
    <br>
    <a class="text-white" href="https://empleo.chaco.gob.ar/informatorio#/" target="_blank"> Informatorio Chaco</a>
  </div>
</footer>

templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand fw-bold fst-italic" href="/">Red Salud Ramon-Carrillo <img src="/static/icons/icon-red-salud.ico" class="img-fluid rounded" alt="red de salud Ramon" style="width: 30px;"> </a>        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active underline-hover" aria-current="page" href="{% url 'articulos:all_articles'%}">Articulos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active underline-hover" href="{% url 'articulos:all_category'%}">Categorías</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active underline-hover" href="{% url 'About:about'%}">Acerca de</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active underline-hover" href="{% url 'contacts:contact'%}">Contacto</a>
                </li>
                {% if user.is_authenticated %}
                <!-- Menú desplegable "Mi Perfil" -->
                <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" href="#" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ user.image.url }}" alt="Mi Perfil" class="profile-image">
                        Perfil
                        {% if user.verified == 'verified' %}
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgb(0, 149, 246)" class="x1lliihq x1n2onr6" viewBox="0 0 40 40">
                            <title>Verificado</title>
                            <path d="M19.998 3.094 14.638 0l-2.972 5.15H5.432v6.354L0 14.64 3.094 20 0 25.359l5.432 3.137v5.905h5.975L14.638 40l5.36-3.094L25.358 40l3.232-5.6h6.162v-6.01L40 25.359 36.905 20 40 14.641l-5.248-3.03v-6.46h-6.419L25.358 0l-5.36 3.094Zm7.415 11.225 2.254 2.287-11.43 11.5-6.835-6.93 2.244-2.258 4.587 4.581 9.18-9.18Z" fill-rule="evenodd"></path>
                        </svg>                        
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="{% url 'usuarios:update_user' %}">Ver Perfil</a></li>
                        {% if user.is_colaborador %}
                            <li><a class="dropdown-item" href="{% url 'articulos:create_category' %}">Crear Categoria</a></li>
                            <li><a class="dropdown-item" href="{% url 'articulos:article_create' %}">Publicar Articulos</a></li>
                        {% endif %}
                        <li><a class="dropdown-item" href="{% url 'usuarios:confirm_logout_user' %}?next={{request.path }}">Cerrar sesión</a></li>
                    </ul>
                </li>
                {% else %}
                <!-- Estos botones se ocultarán en el menú colapsado -->
                <li class="nav-item d-lg-none">
                    <a href="{% url 'usuarios:login_user' %}" class="btn btn-secondary btn-sm">Iniciar sesión</a>
                </li>
                <li class="nav-item d-lg-none">
                    <a href="{% url 'usuarios:signup_user' %}" class="btn btn-primary btn-sm">Registrarse</a>
                </li>
                {% endif %}
            </ul>
        </div>

        <!-- Estos botones estarán visibles solo en modo responsive -->
        {% if not user.is_authenticated %}
        <div class="d-none d-lg-flex">
            <a href="{% url 'usuarios:login_user' %}" class="btn btn-secondary btn-sm me-2">Iniciar sesión</a>
            <a href="{% url 'usuarios:signup_user' %}" class="btn btn-primary btn-sm">Registrarse</a>
        </div>
        {% endif %}
    </div>
</nav>