articulo/urls.py
from django.urls import path
from .views import *


app_name="articulos"

urlpatterns = [

    path('create/', ArtCreateView.as_view(), name="article_create"),

    path('all-articles/', AllArticlesView.as_view(), name="all_articles"),

    path('all-category/', AllCategoriaView.as_view(), name="all_category"),

    path('category/<int:category_id>/', AllCategoriaArticlesView.as_view(), name='all_category_articles'),

    path('create-category/', CategoryCreateView.as_view(), name="create_category"),

    path('<int:pk>/delete-category/', CategoryDeleteView.as_view(), name="delete_category"),

    path('Article/<int:post_id>/', ArtDetailView.as_view(), name="detail_article"),

    path('<int:pk>/update/', ArtUpdateView.as_view(), name="update_article"),

    path('<int:pk>/delete-article/', ArtDeleteView.as_view(), name="delete_article"),

    path('like/<int:post_id>/', LikeHandler.as_view(), name="like"),
    
    path('dislike/<int:post_id>/', DislikeHandler.as_view(), name="dislike"),
]

comentarios/urls.py
from django.urls import path
from .views import *

app_name = 'comentarios'

urlpatterns = [
    path('editar/<int:comment_id>/', CommentUpdateView.as_view(), name='update_comment'),
    path('eliminar/<int:comment_id>/', CommentDeleteView.as_view(), name='delete_comment'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('accounts/', include('usuarios.urls')),
    path('articles/', include('articulo.urls')),
    path('comentarios/', include('comentarios.urls')),
    path('', include('acercaDe.urls')),
    path('', include('contacto.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handling404 = 'views.handling_404'

usuarios/urls.py
from django.urls import path
from .views import *
from . import views

app_name="usuarios"

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login_user'), 
    path('signup/', CustomRegisterUserView.as_view(), {'next_page': None}, name='signup_user'),  
    path('logout/', CustomLogoutView.as_view(), name='logout_user'),  
    path('confirm_logout/', CustomConfirmLogoutView.as_view(), {'next_page': None}, name='confirm_logout_user'),

    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),

    path('update/', CustomUpdateUserView.as_view(), name='update_user'),
    path('change_password/', CustomPasswordChangeView.as_view(), name='change_password'),

    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

templates/Articulos/profile/articles/Art_card.html
<div class="col mb-3"> 
    <div class="card h-100 bg-dark text-white card-project" style="width: 18rem;">
        <img src="{{ article.image.url }}" class="card-img-top" alt="{{ article.title }}" style="max-height: 150px; object-fit: cover;">
        <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted text-center">{{ article.date_published|date:'M d Y' }}</h6>
            <h2 class="fw-bold text-success fs-5 text-center">Título: {{ article.title }}</h2>
            <p class="text-center">Escritor: <a href="{% url 'usuarios:author_detail' article.author.id %}" class="btn btn-outline-primary">{{ article.author.username }}</a></p>
            <p class="text-white card-text text-center">{{ article.content|striptags|truncatechars:100 }}</p>
            {% if user.is_authenticated %}
            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                <a href="{% url 'articulos:detail_article' article.id %}" class="btn btn-success">Leer</a>
                {% if user.is_colaborador %}
                <a href="{% url 'articulos:update_article' article.id %}" class="boton-articulo btn btn-warning ms-2">Editar</a>
                <a href="{% url 'articulos:delete_article' article.id %}" class="boton-articulo btn btn-danger ms-2">Eliminar</a>
                {% endif %}
            </div>
            {% else %}
            <a href="{% url 'articulos:detail_article' article.id %}" class="btn btn-success">Leer</a>
            {% endif %}
        </div>
    </div>
</div>

templates/Articulos/profile/articles/Art_comment.html
{% load crispy_forms_tags %}

<div class="card  bg-white text-black card-project" style="box-shadow: none;">
    <div class="row d-flex align-items-baseline">
        <div class="col-lg-6">
            <div class="container text-center mt-4">

                {% if user.is_authenticated %}
                <div class="row justify-content-start">
                    <div class="col-md-6">
                        <h3 class="fs-5" class="mb-3">Deja un comentario:</h3>
                        <div class="d-flex justify-content-start">
                            <form method="post" class="form-inline justify-content-center">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <div class="d-grid mt-2">
                                    <button type="submit" class="btn btn-primary">Comentar</button>
                                </div>
                            </form>
                        </div>
                        {% else %}
                        <div class="container text-center">
                            <p class="mb-4"> <a href="{% url 'usuarios:login_user' %}"
                                    class="btn btn-secondary btn-sm">Iniciar sesión</a> Haz un comentario!!!</p>
                        </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <h3 class="fs-5" class="mb-3 ">Comentarios:</h3>
            <ul class="bg-white  list-unstyled  bg-white" style="max-height: 300px; overflow-y: auto;">
                {% for comment in comments %}
                <li class="mb-3">
                    <div class="border p-3"> <!-- Caja para resaltar el contenido -->
                        <img src="{{ comment.author.image.url }}" alt="{{ comment.author.username }}"
                            class="rounded-circle" width="40" height="40"/>
                        <p>
                            <strong>{{ comment.author.username }}</strong> - {{ comment.created_at|date:"M d Y H:i"}}
                        </p>
                        {{ comment.content }}
                        {% if user.is_authenticated %}
                        {% if user.is_colaborador or user == comment.author %}
                        <!-- Mostrar el botón de editar solo para el autor del comentario -->
                        {% if user == comment.author %}
                        <a href="{% url 'comentarios:update_comment' comment.id %}" class="btn btn-warning"> <i
                                class="bi bi-pencil-fill"></i> </a>
                        {% endif %}
                        <!-- Mostrar el botón de eliminar para el autor del comentario y colaboradores -->
                        <a href="{% url 'comentarios:delete_comment' comment.id %}" class="btn btn-danger"> <i
                                class="bi bi-trash"></i> </a>
                        {% endif %}
                        {% endif %}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

</div>

templates/Articulos/profile/articles/Art_create.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<main class="container">
{% if user.is_authenticated and user.is_colaborador %}
  <h1  class=" mb-4 text-center fs-6 text-decoration-underline">Crear Artículo</h1>
    <div class="row justify-content-center">
      <div class="col-md-6">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{form|crispy}}
            <div class="d-grid mt-4">
              <button class="btn btn-primary" type="submit">Guardar cambios</button>
            </div>
            <div class="d-grid mt-4">
              <a href="{% url 'articulos:all_articles' %}" class="btn btn-secondary">Cancelar</a>
            </div>
          </form>
          <p> 
              {% else %}
              <p>Esta página solo está disponible para colaboradores. Por favor, inicia sesión o regístrate como colaborador.</p>
              <p><a href="{% url 'usuarios:login_user' %}">Iniciar sesión</a> | <a href="{% url 'usuarios:signup_user' %}">Registrarse</a></p>
              {% endif %}
          </p> 
      </div>      
    </div>     
</main>          
{% endblock %}

templates/Articulos/profile/articles/Art_delete.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block content %}
<main class="container d-flex justify-content-center align-items-center vh-100">
  <div class="col-md-6">
    <h1 class="mb-4 text-center fs-6">¿Estás seguro de que deseas eliminar el siguiente artículo?</h1>
    <h2 class="text-center">{{ object.title }}</h2>
    <p class="text-center" >{{ object.content|striptags |truncatechars:100 }}</p>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form|crispy}}
      <div class="d-grid mt-4">
        <button class="btn btn-danger" type="submit">Eliminar</button>
      </div>
      <div class="d-grid mt-4">
        <a href="{% url 'articulos:all_articles' %}" class="btn btn-secondary">Cancelar</a>
      </div>
    </form>
  </div>
</main>
{% endblock %}

templates/Articulos/profile/articles/Art_detail.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<!-- Mesaje de actualizacion de un articulo -->
{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'success' %}
      <div class="alert alert-success alert-custom-success" role="alert" id="success-alert">
        <h4 class="alert-heading">¡Bien hecho!</h4>
        <p>{{ message }}</p>
        <hr>
        <p class="mb-0">¡Excelente trabajo!</p>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}

<script src="{% static 'js/timeMessageUpdateArt.js' %}"></script>
<!-- ############################################################ -->

<!-- Seccion de vista del contenido de un articulo -->
<p class="my-2 ps-5">
  <span class="text-muted">Author:</span> <a href="{% url 'usuarios:author_detail' article.author.id %}" class="text-muted" style="p-0">{{ article.author.username }}</a>
  <span class="text-muted">|</span> {{ article.date_published }}
  <span class="text-muted">|</span> {{ article.category }}
</p>

<h1 class="my-4 d-flex justify-content-center align-items-center">{{ article.title }}</h1>

<div class="d-flex justify-content-center ">
  <img src="{{ article.image.url }}" alt="{{ article.title }}" class="img-fluid w-75">
</div>

{% include "Articulos/profile/articles/Art_reacction.html" %}

<!-- ############################################################ -->


<!-- Seccion de Botón de "like" | "Dislike" -->
<div class="my-4">
  <p class="d-flex justify-content-center align-items-center  card bg-white" style="box-shadow: none; max-width: auto;">{{ article.content }}</p>
</div>
<!-- ############################################################ -->

<!-- Seccion de comentar un articulo -->
{% include 'Articulos/profile/articles/Art_comment.html' %}
<!-- ############################################################ -->

{% endblock %} 

templates/Articulos/profile/articles/Art_form_search.html
<form class="d-flex flex-wrap justify-content-center align-items-center my-3" method="get" action="{% url 'articulos:all_articles' %}">
    {% csrf_token %}
    <div class="input-group" style="max-width: 400px;"> <!-- Puedes ajustar el valor de max-width según tus necesidades -->
        <input name="q" class="form-control" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-success me-2" type="submit">Buscar</button>
    </div>
    <div class="d-flex align-items-center">
        <!-- Filtro por Categoría -->
        <select name="category" class="form-select me-2" style="width: 150px;">
            <option value="" selected>Categoría</option>    
            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        <!-- Filtro por Autor -->
        <select name="author" class="form-select me-2">
            <option value="" selected>Autor</option>
            {% for author in authors %}
                <option value="{{ author.id }}">{{ author.username }}</option>
            {% endfor %}
        </select>
    </div>
</form>
<div class="d-flex justify-content-center mb-3">
    <div class="btn-group" role="group">
        <a class="btn btn-sm btn-secondary btn-rounded" href="{% url 'articulos:all_articles' %}?sort_by=asc">Más antiguos</a>
        <a class="btn btn-sm btn-secondary btn-rounded" href="{% url 'articulos:all_articles' %}?sort_by=desc">Más recientes</a>
        <a class="btn btn-sm btn-secondary btn-rounded" href="{% url 'articulos:all_articles' %}?sort_by=alpha_asc">A-Z</a>
        <a class="btn btn-sm btn-secondary btn-rounded" href="{% url 'articulos:all_articles' %}?sort_by=alpha_desc">Z-A</a>
    </div>
</div>

templates/Articulos/profile/articles/Art_list.html
{% comment %} {% extends 'layout.html' %}

{% block content %}
    <h1>Listado de Artículos</h1>

    <ul>
        {% for article in articles %}
            <li>
                <h2>{{ article.title }}</h2>
                <p>{{ article.content }}</p>
                <!-- Agrega más detalles o campos del artículo aquí, si es necesario -->
            </li>
        {% endfor %}
    </ul>
{% endblock %} {% endcomment %}

{% extends 'layout.html' %}

{% block content %}
  <h1>Listado de Artículos</h1>
  <ul>
    {% for article in articles %}
      <li>
        <h2><a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a></h2>
        <p>{{ article.content }}</p>
        <!-- Agrega más detalles o campos del artículo aquí, si es necesario -->
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/Articulos/profile/articles/Art_pagination.html
<div class="pagination d-flex justify-content-center align-items-center">
    <div class="pagination-container">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if page.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; Anterior</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">Anterior</a></li>
                {% endif %}

                <li class="page-item disabled"><span class="page-link">Página {{ page.number }} de {{ page.paginator.num_pages }}.</span></li>

                {% if page.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Siguiente</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">Última &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div> 

templates/Articulos/profile/articles/Art_reacction.html
{% if user.is_authenticated %}
<div class="container text-center mt-4">
    <div class="btn-group" role="group" aria-label="Reacciones">
        <div class="d-flex justify-content-center">    
            <!-- Botón de "like" -->
            <form method="post" action="{% url 'articulos:like' article.pk %}" class="form-inline justify-content-center">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                    <button type="submit" class="btn btn-primary mx-2">
                        <i class="bi bi-hand-thumbs-up"></i>
                    </button>
                    <!-- Contador de likes -->
                    <span class="badge bg-primary">{{ article.likes.count }}</span>
            </form>

            <!-- Botón de "dislike" -->
            <form method="post" action="{% url 'articulos:dislike' article.pk %}" class="form-inline justify-content-center">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                    <button type="submit" class="btn btn-danger mx-2">
                        <i class="bi bi-hand-thumbs-down"></i>
                    <!-- Contador de dislikes -->
                    <span class="badge bg-danger">{{ article.dislikes.count }}</span>
            </form>
        </div>
    </div>
</div>
{% endif %}

templates/Articulos/profile/articles/Art_update.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}


{% block content %}
<main class="container">
  <h1  class=" mb-4 text-center fs-6 text-decoration-underline">Actualizar el Artículo</h1>
    <div class="row justify-content-center">
      <div class="col-md-6">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <div class="d-grid mt-4">
          <button class="btn btn-primary" type="submit">Guardar cambios</button>
        </div>
        <div class="d-grid mt-4">
          <a href="{% url 'articulos:detail_article' post_id=article.pk %}" class="btn btn-secondary">Cancelar</a>
        </div>
      </form>
    </div>
  </div>
</main>      
{% endblock %}

templates/Articulos/profile/articles/all_articles.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}


<!-- Formulario de búsqueda -->
{% include 'Articulos/profile/articles/Art_form_search.html' %}
<!-- ############################################################################### -->

<!-- Seccion del listado de articulos -->
<div class="center-content d-flex justify-content-center align-items-center">
    <h3 class="fw-bold text-center">Todos los Articulos</h3>
    <div class="row g-4 justify-content-center"> 
        {% for article in page %}
            {% include 'Articulos/profile/articles/Art_card.html' %}
        {% endfor %}
    </div>
</div> 
<!-- ############################################################################### -->


<!-- Paginacion para los articulos -->
{% include 'Articulos/profile/articles/Art_pagination.html' %}

<!-- ############################################################################### -->

{% endblock %}